metadata:
  favicon: ''
  title: git app
  description: ''
  breakpoints:
    - name: xl
      width:
        value: 100
        unit: '%'
    - name: xs
      width:
        value: 800
        unit: px
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
